In [2]:
import numpy as np

In [4]:
np1 = np.array([1,2,3,'s1','s2',2+2,3*2,{'name':'arc'}])
np1

array([1, 2, 3, 's1', 's2', 4, 6, {'name': 'arc'}], dtype=object)

In [5]:
type(np1)

numpy.ndarray

In [7]:
np2 = np.array(list(range(1,50,2)))
np2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [13]:
l1 = list(range(1,50,1))
l1

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [14]:
Np2 = np.array([[1,2,3],[4,5,6]])

In [15]:
print(Np2)

[[1 2 3]
 [4 5 6]]


In [16]:
print(np1)
print()
print(np2)
print()
print(Np2)

[1 2 3 's1' 's2' 4 6 {'name': 'arc'}]

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]

[[1 2 3]
 [4 5 6]]


In [19]:
print(f'np1.shape() = {np1.shape}')
print(f'np2.shape() = {np2.shape}')
print(f'Np2.shape() = {len(Np2)}')

np1.shape() = (8,)
np2.shape() = (25,)
Np2.shape() = 2


In [24]:
Np3 = np.array([[1,2,3],[4,5,6]])

In [28]:
Np2[1,2] = 9
Np2

array([[1, 2, 3],
       [4, 5, 9]])

In [32]:
mat2 = np.arange(10,100,5)
print(f'mat2 = {mat2}')
l1range = np.array(range(10,100,5))
print(f'l1range = {l1range}')

mat2 = [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
l1range = [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [33]:
mat3 = np.linspace(0,10,20)
print(mat3)
print(mat3.shape)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
(20,)


In [34]:
mat4 = np.random.rand(5,5)
print(mat4)

[[0.33516836 0.3016264  0.46383896 0.12284216 0.38300823]
 [0.15996466 0.22585134 0.53107668 0.34901428 0.1712041 ]
 [0.11162295 0.4109335  0.97601026 0.17122786 0.67681512]
 [0.15275182 0.3776422  0.59024076 0.49249719 0.68877373]
 [0.23216954 0.90927279 0.54359021 0.42935498 0.37918876]]
