# Numpy


In [17]:
import numpy as np

In [18]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [19]:
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
type(np1)

numpy.ndarray

In [21]:
mat1 = np.array([[1,2,3], [3,4,6]])

In [22]:
mat1

array([[1, 2, 3],
       [3, 4, 6]])

In [23]:
np1.shape

(10,)

In [24]:
mat1.shape

(2, 3)

In [25]:
mat1.dtype

dtype('int32')

In [26]:
np1.dtype

dtype('int32')

In [27]:
mat1[0,0] = 11

In [28]:
mat1

array([[11,  2,  3],
       [ 3,  4,  6]])

In [29]:
mat1[0,2] = "text"

ValueError: invalid literal for int() with base 10: 'text'

In [ ]:
mat2 = np.arange(0,10,1)

In [ ]:
mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mat3 = np.linspace(0,10,20)

In [ ]:
mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
mat3.shape

(20,)

In [ ]:
mat4 = np.random.rand(5,5)

In [ ]:
mat4

array([[0.61761218, 0.42395279, 0.27059258, 0.20472064, 0.46942191],
       [0.06158964, 0.45174256, 0.00635951, 0.64404021, 0.49920793],
       [0.41982622, 0.92055791, 0.83843585, 0.01338051, 0.95010242],
       [0.40354726, 0.58540865, 0.40085136, 0.46323758, 0.64874763],
       [0.04230792, 0.9692767 , 0.17822249, 0.85345217, 0.87258853]])

In [ ]:
mat5= np.random.randn(5,5)

In [ ]:
mat5

array([[ 1.84704494, -0.03987036, -1.45075873,  0.69943126,  0.62793796],
       [-0.01655361,  0.99966914,  0.77977907, -0.17830769,  1.23840825],
       [ 1.4976991 ,  0.87666657, -2.31454295, -0.02741284, -0.55065694],
       [-0.76793942,  1.56414697,  0.64166878,  0.36633073,  0.0706921 ],
       [-1.32667076, -0.92510432,  0.8886739 , -1.10535478,  0.79368455]])

In [ ]:
mat5[0,0]

1.847044937791627

In [ ]:
mat5[0,1]

-0.03987036468165672

In [ ]:
mat5[0:3]

array([[ 1.84704494, -0.03987036, -1.45075873,  0.69943126,  0.62793796],
       [-0.01655361,  0.99966914,  0.77977907, -0.17830769,  1.23840825],
       [ 1.4976991 ,  0.87666657, -2.31454295, -0.02741284, -0.55065694]])

In [ ]:
mat5[0:3,:]

array([[ 1.84704494, -0.03987036, -1.45075873,  0.69943126,  0.62793796],
       [-0.01655361,  0.99966914,  0.77977907, -0.17830769,  1.23840825],
       [ 1.4976991 ,  0.87666657, -2.31454295, -0.02741284, -0.55065694]])

In [ ]:
mat5[0:3,1:2]

array([[-0.03987036],
       [ 0.99966914],
       [ 0.87666657]])

# ***Numpy***

**1. Array Creation**

- `np.array`: Creates a NumPy array, which is a multi-dimensional, homogeneous data structure that can hold various types of elements.

https://numpy.org/doc/stable/reference/generated/numpy.array.html

In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", arr)

NumPy Array: [1 2 3 4 5]


- `np.zeros`: Generates an array filled with zeros of a specified shape.

https://numpy.org/doc/stable/reference/generated/numpy.zeros.html

In [ ]:
# Create an array of zeros
zeros_arr = np.zeros((3, 4))  # 3 rows, 4 columns
print("Zeros Array:")
print(zeros_arr)

Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



- `np.ones`: Creates an array filled with ones of a specified shape.

https://numpy.org/doc/stable/reference/generated/numpy.ones.html

In [ ]:
# Create an array of ones
ones_arr = np.ones((2, 3))  # 2 rows, 3 columns
print("Ones Array:")
print(ones_arr)

Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]]


- `np.random.rand`: Generates random numbers in a specified shape from a uniform distribution over [0, 1).

https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html

In [ ]:
# Generate random numbers between 0 and 1
random_arr = np.random.rand(3, 2)  # 3 rows, 2 columns
print("Random Array:")
print(random_arr)


Random Array:
[[0.26388855 0.38596886]
 [0.68386045 0.82163579]
 [0.50704366 0.65502226]]


**2. Array Operations**

In [ ]:
# Create two NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

- `np.add`: Element-wise addition of two arrays or a scalar and an array.

https://numpy.org/doc/stable/reference/generated/numpy.add.html

In [ ]:
# Perform element-wise addition
add_result = np.add(arr1, arr2)
print("Addition Result:", add_result)


Addition Result: [5 7 9]


- `np.subtract`: Element-wise subtraction of one array from another or a scalar from an array.

https://numpy.org/doc/stable/reference/generated/numpy.subtract.html

In [ ]:
# Perform element-wise subtraction
subtract_result = np.subtract(arr2, arr1)
print("Subtraction Result:", subtract_result)

Subtraction Result: [3 3 3]


- `np.multiply`: Element-wise multiplication of two arrays or a scalar and an array.

https://numpy.org/doc/stable/reference/generated/numpy.multiply.html

In [ ]:
# Perform element-wise multiplication
multiply_result = np.multiply(arr1, arr2)
print("Multiplication Result:", multiply_result)

Multiplication Result: [ 4 10 18]


- `np.divide`: Element-wise division of one array by another or a scalar by an array.

https://numpy.org/doc/stable/reference/generated/numpy.divide.html

In [ ]:
# Perform element-wise division
divide_result = np.divide(arr2, arr1)
print("Division Result:", divide_result)

Division Result: [4.  2.5 2. ]


- `np.sqrt`: Computes the element-wise square root of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html

In [ ]:
# Compute element-wise square root
arSq = np.array([2,4,6])
sqrt_result = np.sqrt(arSq)
print("Square Root Result:", sqrt_result)

Square Root Result: [1.41421356 2.         2.44948974]


In [ ]:
# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

- `ndarray.shape`: Returns a tuple representing the dimensions of the array.

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html

In [ ]:
# Get the shape of the array
shape = arr.shape
print("Array Shape:", shape)

Array Shape: (2, 3)


- `ndarray.size`: Returns the total number of elements in the array

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.size.html

In [ ]:
# Get the total number of elements
size = arr.size
print("Array Size:", size)

Array Size: 6


- `ndarray.ndim`: Returns the number of dimensions (axes) of the array.

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.ndim.html

In [ ]:
# Get the number of dimensions
ndim = arr3.ndim
print("Number of Dimensions:", ndim)

Number of Dimensions: 1


- `ndarray.dtype`: Returns the data type of the elements in the array.

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.dtype.html

In [ ]:
# Get the data type of the elements
dtype = arr.dtype
print("Data Type:", dtype)

Data Type: int32


- Indexing (`ndarray[index]`): Allows you to access a specific element in a NumPy ndarray using its index value. The index can be an integer or a tuple of integers for multidimensional arrays.

https://numpy.org/doc/stable/reference/arrays.indexing.html

In [ ]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Indexing: Access a specific element
element = arr_1d[2]  # Access the element at index 2 (3rd element)
print("Indexed Element:", element)

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indexing: Access an element in a 2D array
element_2d = arr_2d[1, 2]  # Access the element at row 1, column 2 (6)
print("Indexed 2D Element:", element_2d)



Indexed Element: 3
Indexed 2D Element: 6


- Slicing (`ndarray[start:end]`): Allows you to extract a portion of a NumPy ndarray using a range of indices. The `start` index is inclusive, and the `end` index is exclusive. This creates a new ndarray that contains the specified slice of elements.

https://numpy.org/doc/stable/reference/arrays.indexing.html

In [ ]:
# Slicing: Extract a portion of a 1D array
sliced_1d = arr_1d[1:4]  # Extract elements from index 1 to 3 (exclusive)
print("Sliced 1D Array:", sliced_1d)

# Slicing: Extract a portion of a 2D array
sliced_2d = arr_2d[0:2, 1:3]  # Extract rows 0 to 1 and columns 1 to 2
print("Sliced 2D Array:")
print(sliced_2d)

Sliced 1D Array: [2 3 4]
Sliced 2D Array:
[[2 3]
 [5 6]]


5. Aggregation and Statistics:

- `np.sum`: Computes the sum of array elements along a specified axis or over the entire array.

https://numpy.org/doc/stable/reference/generated/numpy.sum.html

In [ ]:
# Create a 1D array
arr = np.array([4, 2, 9, 5, 1, 8, 6, 3, 7])

# Compute the sum of array elements
sum_result = np.sum(arr)
print("Sum:", sum_result)

Sum: 45


- `np.mean`: Calculates the mean (average) of array elements along a specified axis or over the entire array.

https://numpy.org/doc/stable/reference/generated/numpy.mean.html

In [ ]:
# Calculate the mean of array elements
mean_result = np.mean(arr)
print("Mean:", mean_result)

Mean: 5.0


- `np.median`: Computes the median (middle value) of array elements along a specified axis or over the entire array.

https://numpy.org/doc/stable/reference/generated/numpy.median.html

In [ ]:
# Calculate the median of array elements
median_result = np.median(arr)
print("Median:", median_result)

Median: 5.0


- `np.std`: Calculates the standard deviation of array elements along a specified axis or over the entire array.

https://numpy.org/doc/stable/reference/generated/numpy.std.html

In [ ]:
# Calculate the standard deviation of array elements
std_result = np.std(arr)
print("Standard Deviation:", std_result)

Standard Deviation: 2.581988897471611


- `np.min`: Finds the minimum value among array elements along a specified axis or over the entire array.

https://numpy.org/doc/stable/reference/generated/numpy.min.html

In [ ]:
# Find the minimum value in the array
min_result = np.min(arr)
print("Minimum:", min_result)

Minimum: 1


- `np.max`: Finds the maximum value among array elements along a specified axis or over the entire array.

https://numpy.org/doc/stable/reference/generated/numpy.max.html

In [ ]:
# Find the maximum value in the array
max_result = np.max(arr)
print("Maximum:", max_result)

Maximum: 9


**6. Array Manipulation:**

- `ndarray.reshape()`: Reshapes an ndarray to a specified new shape while maintaining the original data. The total number of elements must remain unchanged.

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html

In [ ]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape the array to a different shape
reshaped_arr = arr.reshape(3, 2)  # Reshaping to 3 rows, 2 columns
print("Reshaped Array:")
print(reshaped_arr)

Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]


- `ndarray.transpose()`: Transposes the dimensions of an ndarray, effectively flipping rows and columns.

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.transpose.html

In [ ]:
# Transpose the array
transposed_arr = arr.transpose()  # Transpose rows and columns
print("Transposed Array:")
print(transposed_arr)

Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


**7. Loading and Saving Data**

- `np.load`: Loads and returns an ndarray or a dictionary of ndarrays from a binary file (usually with a `.npy` extension) created using np.save.

https://numpy.org/doc/stable/reference/generated/numpy.load.html

In [ ]:
# Create an ndarray
arr = np.array([1, 2, 3, 4, 5])

# Save the ndarray to a file
np.save('saved_array.npy', arr)


print("Original Array:", arr)

Original Array: [1 2 3 4 5]


- `np.save`: Saves an ndarray or a dictionary of ndarrays to a binary file with the `.npy` extension, preserving the data and metadata of the array(s).

https://numpy.org/doc/stable/reference/generated/numpy.save.html

In [ ]:
# Load the saved ndarray from the file
loaded_arr = np.load('saved_array.npy')

print("Loaded Array:", loaded_arr)

Loaded Array: [1 2 3 4 5]


**8. Handling Missing Data:**

- `np.nan`: Represents a floating-point "Not a Number" value, often used to indicate missing or undefined data in arrays.

https://numpy.org/doc/stable/reference/constants.html#numpy.nan

In [ ]:
# Create an array with NaN values
arr_with_nan = np.array([1.0, np.nan, 3.0, np.nan, 5.0])

- `np.isnan`: Returns a boolean array indicating which elements of an array are NaN (Not a Number).


https://numpy.org/doc/stable/reference/generated/numpy.isnan.html

In [ ]:
# Check for NaN values using np.isnan
nan_mask = np.isnan(arr_with_nan)
print("NaN Mask:", nan_mask)

NaN Mask: [False  True False  True False]


- `np.where`: Returns the indices where a specified condition is met in an array, or returns values from two arrays based on a condition.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
# Create an array with conditions
condition = np.array([True, False, True, False, True])

# Use np.where to get indices where the condition is True
indices = np.where(condition)
print("Indices where condition is True:", indices)

# Use np.where to get values based on a condition
values = np.where(condition, arr_with_nan, 0)
print("Values based on condition:", values)

Indices where condition is True: (array([0, 2, 4], dtype=int64),)
Values based on condition: [1. 0. 3. 0. 5.]
